### ISSUE TITLE
[HRTIM ?] PWM glitches when using extreme duty cycle values 0.0 and 1.0

### ISSUE THREAD

**Issue by pierre-haessig** [owntech-foundation/Core#144]
# [HRTIM ?] PWM glitches when using extreme duty cycle values 0.0 and 1.0

Nov-Dec 2025

Using the Ownverter 1.1 board, with 1.0 Power API code, there are glitches when using duty cycle values equal or close to 0.0 or 1.0.

Here are two cases, with slightly different symptoms. Both were created using  three-phase islanded inverter application https://github.com/pierre-haessig/ownverter-islanded/tree/completed (using the `completed` branch, since main is the student version with a few blanks to be filled.)

- sinusoidal duty cycles PWM
- square wave modulation

In all cases, experimental conditions are: three-phase inverter connected through an inductive filter (630 µF) to either a balanced R=10Ω load or R+L load (L=76 mH).

In all cases, the control task period is 0.1 ms = 100 µs (10 kHz)

## Sinusoidal duty cycles PWM

In this application, with pure R load, the duty cycles are [computed](https://github.com/pierre-haessig/ownverter-islanded/blob/completed/src/main.cpp#L291) as:

```Cpp
duty_a = duty_offset + duty_amplitude * ot_sin(v_angle);
duty_b = duty_offset + duty_amplitude * ot_sin(v_angle - 2.0/3.0*PI);
duty_c = duty_offset + duty_amplitude * ot_sin(v_angle - 4.0/3.0*PI);
```

with `duty_offset` set to 0.5 and `duty_amplitude` set to 0.5, so that the duties reach 0 or 1 once per electric period (50 Hz/20 ms).

Here are the resulting oscilloscope captures, with incremental zoom around the top of the sinusoid:

- yellow-(C1): inverter voltage (phase to PGND or phase to Neutral, I don't remember)
- pink (C2): current through load
- green and cyan (C3, C4): swiching signals (CHA1 and CHA2 pins)

| ![Ownverter_islanded_sine_duty-glitch_2025-11-10](https://github.com/user-attachments/assets/012acc23-cd3a-4ab3-bbe4-0e06e5f9e30a) | ![Ownverter_islanded_sine_duty-glitch_2025-11-10-zoom1](https://github.com/user-attachments/assets/26673d7b-65e4-40be-adb2-cd68c32c6f88) |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| ![Ownverter_islanded_sine_duty-glitch_2025-11-10-zoom2](https://github.com/user-attachments/assets/89ef343f-5ce5-49a4-8408-56097faf6651) | ![Ownverter_islanded_sine_duty-glitch_2025-11-10-zoom3](https://github.com/user-attachments/assets/ae0e7b6b-2873-4352-9666-b101a09c7e4a) |

Observations: 

- the sinusoidal current  is heavily perturbed 6 times per period, in fact each time one of the three phases has its duty cycle close to 0 or 1.
- zooming to the top of the sinusoid, we see that the glitches corresponds to undue switchings while the PWM output should stay constant.
- the switchings happen at integer multiple of the control period (100 µs), so that they are linked to calls to [setDutyCycle](https://github.com/pierre-haessig/ownverter-islanded/blob/completed/src/main.cpp#L331), with changing values of duty

## Square wave modulation

The square wave modulation is done by [setting the duty cycle to 0.0 or 1.0 on appropriate half periods](https://github.com/pierre-haessig/ownverter-islanded/blob/completed/src/main.cpp#L296): 

```Cpp
if (square_wave) {
    if (v_angle <= PI) duty_a = 1.0;
    else duty_a = 0.0;
    if (ot_modulo_2pi(v_angle - 2.0/3.0*PI) <= PI) duty_b = 1.0;
    else duty_b = 0.0;
    if (ot_modulo_2pi(v_angle - 4.0/3.0*PI) <= PI) duty_c = 1.0;
    else duty_c = 0.0;
}
```

The resulting oscilloscope captures are obtained here with a pure R load (still with L filter, so that L/R = 63 µs).

Results are even more suprising than with sine PWM.

![Ownverter_islanded_square_duty-glitch_2025-11-10](https://github.com/user-attachments/assets/0d7761b3-f276-4931-a469-971cb64c68a3)

| Zoom around a half period switch point                       | Zoom around a constant duty region                           |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| ![Ownverter_islanded_square_duty-glitch_2025-11-10_zoom-a1](https://github.com/user-attachments/assets/12791837-7ab9-49c5-b2e1-9b2e38d44b38) | ![Ownverter_islanded_square_duty-glitch_2025-11-10-zoom-b1](https://github.com/user-attachments/assets/59244f03-1c7c-4642-9799-ccb67a86be7b) |
| ![Ownverter_islanded_square_duty-glitch_2025-11-10_zoom-a2](https://github.com/user-attachments/assets/06bbf837-8430-4e6b-ae63-2feb916f8223) |                                                              |
| ![Ownverter_islanded_square_duty-glitch_2025-11-10_zoom-a3](https://github.com/user-attachments/assets/ac4503de-d268-4178-8497-6a5a207b0e42) | ![Ownverter_islanded_square_duty-glitch_2025-11-10-zoom-b2](https://github.com/user-attachments/assets/35f6f743-0289-4d24-8818-fce0f3f33a0b) |
| ![Ownverter_islanded_square_duty-glitch_2025-11-10_zoom-a4](https://github.com/user-attachments/assets/f58061f1-d642-41f3-ac48-d224044d5f0f) | ![Ownverter_islanded_square_duty-glitch_2025-11-10-zoom-b3](https://github.com/user-attachments/assets/6d4f57cc-fa75-442f-aee3-cd3904539a1a) |

Observations:

- despite the fact that the duty is kept constant, there almost are periodic glitches (every 300 to 400 µs)
  - it doesn't seem periodic with the control task
- even more surprising, **no glitch is visible on the PWM output**  (CHA1 and CHA2 pins) which are constant!

**Comment by luizvilla** [comment]
Hello @pierre-haessig, 

       Thank you for the issue. I'm going to work on it today. 
       It seems to me there are two separate issues here: 
- [ ] A recurrent switching even when the PWM signal from the microcontroller is stable
- [x] A toggle between 0 and 1 for the PWM signals from the microcontroller when values are close to 0 and 1.  

I suspect the first one is a driver issue. Could it be that the driver of the mosfets forces switching ? @jalinei 

The second one looks like a software glitch due to the way in which the 1 and 0 are done. I'll look into it.

**Comment by luizvilla** [comment]
I found the second error. 

When the duty cycle approaches 1, there is indeed a software glitch. 

Here's the duty cycle at 0.9975

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/96deaa1d-2858-4a2b-9748-6f60d32cddbf" />

Here's the duty cycle at 0.9976

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/c6918762-c44d-45e3-8a4e-138642a26d20" />

And here's the duty cycle at 0.9997

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/96de316e-1ee1-40dd-b1fa-2b1e3b1c2920" />

You can reproduce the error by simply using your `main` branch code but raising the duty cycle by 0.0001 at a time. 

The explanation lies on the fact that the HRTIM PWM's on the STM32G4 **do NOT** support 1/0 mode. 
We implemented it by swapping the two outputs. However, we only swap when we are within 3 counts of the final clock, as per the documentation and the glitch resolution here #110 .

Apparently the criteria for going into swap is too small. 
I will enlarge it and test a solution to the problem.

**Comment by luizvilla** [comment]
I just did another test, looking up the raw values after which the HRTIM gets the glitch. 
It is not 3, it is 30...

```
POW: duty a= 50% o= 50% @50 Hz | Vh  0.00 V, Ih -10.00 A, D1 0.997699 , D1R 13568 , P1 13600, 
```

Where : 
- duty a is the duty cycle in %
- o is the offset
- Vh and Ih are measurements (off because I'm using a spin board for testing)
- D1 is the duty cycle as a float between 1 and 0
- D1R is the duty cycle in uint
- P1 is the period in uint

The answer, obviously, was right in front of my eyes: 

<img width="748" height="307" alt="Image" src="https://github.com/user-attachments/assets/1be3e927-6652-45cb-a058-05d4976874d4" />

This table shows the maximum value depending on the pre-scaler that is set on the clock. 

The solution is thus to create a table with these values and use it when testing the moment to swap.

**Comment by luizvilla** [comment]
I implemented a solution on #145. 

@pierre-haessig Can you please : 
- add my fork of the Core to your VSCode git graph, 
- checkout [my branch](https://github.com/luizvilla/Core/tree/hrtim_patch), 
- put your main.cpp code in it and 
- put the results here


Best
Luiz

**Comment by pierre-haessig** [comment]
Hello Luiz, thanks a lot for working on the PWM glitches. I've finally made the test of your branch.

Results:
- unfortunately the bug persists 😢 
- but the good news is that your changes have positive effect: half of the glitches are reduced!

See results below (left: old, right: your hrtrim_pathc branch). Specifically, I see:
-  highly reduced glitches 3 times per period which corresponds to regions where the duty cycle is close to 1.0 on one of the three phases
- on the other hand, I see no changes for the other 3 times per period where the duty cycle is close to 0.0

<img width="1024" height="330" alt="Image" src="https://github.com/user-attachments/assets/d8abbe36-9d80-4bbb-b548-1ffe974fa9c0" />

--- 

Also, there is a minor issue with your branch which may actually mean that there are missing bits: in platformio.ini, I cannot select the proper shield

```
# Selected Shield Name and Version
board_shield = ownverter
board_shield_version = 1_1_0
```

ownverter version 1_1_0 is on available, only 1_0_0.

**Comment by luizvilla** [comment]
@pierre-haessig Thank you for the feedback. 
Can you please try on the square wave modulation please?

**Comment by pierre-haessig** [comment]
Hello @luizvilla, I've tried with the square wave modulation. The result is similarly glitchy, but not exactly similar.

<img width="1024" height="330" alt="Image" src="https://github.com/user-attachments/assets/5720ce38-8ec3-46a8-b33e-f6d7d57a3513" />

Here is a zoom on the region which is different. In some regions, there are twice as many glitches:

<img width="1024" height="600" alt="Image" src="https://github.com/user-attachments/assets/a5836da4-607c-41cb-b6a0-de5a1c321664" />

**Comment by pierre-haessig** [comment]
In fact after a few more measurements with the square wave, I'm not so sure the minor glitch changes (with the "double glitch per period") can be attributed to code change, because it can changes over the course of some tens of seconds. What is constant is the major periodic glitch (which period is about 370 to 380 µs).

**Comment by pierre-haessig** [comment]
Hello, any update on the topic of 0.0 and 1.0 duty cycles?

**Comment by luizvilla** [comment]
Hello @pierre-haessig, 

       I made a new series of tests.

### My setup
- I use an ownverter in with no load
- My test code is the [main.cpp attached.](https://github.com/user-attachments/files/26679637/main.cpp)  

### Procedure

1. I ran the system in square wave mode at 50Hz. 
2. I used a max duty cycle of 0.93
3. I raised the duty cycle manually to reach 1.0
4. I measured only `Va` and `duty_a` using scope mimicy and an USB oscilloscope. I used another oscilloscope

My results with 0.93: 

**From scope mimicry**
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/696243fd-d2da-47f7-979b-a5b0a2f153c1" />

**From the oscilloscope**

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/f85f591b-d48c-4e36-a7d0-51da26d696b5" />

My results with 0.95: 

**From scope mimicry**
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/f0fd453c-f64f-4291-b211-12b771a49c40" />

**From the oscilloscope**

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/6268b63b-4ba6-4999-a8ef-61899c9a545f" />

My results with 0.96: 


**From scope mimicry**
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/3fae4871-b47e-4835-a08f-d1ddfe877aca" />

**From the oscilloscope**

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/01d73035-dba9-462e-97dc-420b4b511589" />

And with 1.0: 

**From scope mimicry**
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/191abe5e-291e-49f6-b61c-eda6633b09bb" />

**From the oscilloscope**

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/2144a71f-0f89-4d4c-904e-8fd2b0b73dce" />

### Result

- I do not reproduce the same glitches as you (even looking with an oscilloscope). 
- When reaching above a certain duty cycle level, the square wave collapses. 


### Second test

When I raise the frequency up to 1.6kHz I get: 

**For the scope mimicry**
<img width="2560" height="1364" alt="Image" src="https://github.com/user-attachments/assets/670e0448-9bd4-4eaa-8560-97f51cbdf576" />
_The offset is normal, since the data is acquired at the control loop and there is a delay between changing the duty cycle and acquiring the voltage value_

**For the oscilloscope**

<img width="800" height="503" alt="Image" src="https://github.com/user-attachments/assets/12836b39-63a2-4605-a689-ca7cf2c77997" />

### Result test 2
- It seems to me that what I see is that when the duty cycle is too high you have a bootstrap issue, where the bootstrap capacitor of the high side can not sustain the voltage for too long and collapses. 

Can you try to reproduce this test on your side?
